# Properties applied for any profile

server:
    port: 8080

spring:
    profiles:
      active: dev
    queries:
      users-query: select username, password from users where username=?
      roles-query: select u.username, r.role from users u inner join user_role ur on(u.id=ur.user_id) inner join role r on(ur.role_id=r.id) where u.username=?
    mail:
      apikey: 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
      formularedir: /home/yamaha/formulare
---

# Development profile

spring:
    profiles: dev
    main:
        web-environment: false
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
        username: postgres
        password: 
        driver-class-name: org.postgresql.Driver
        dialect: org.hibernate.dialect.PostgreSQLDialect
        max-active: 5
        max-pool: 10
        max-idle: 0
    jpa:
        hibernate:
            ddl-auto: update  # this will create the DB schema locally
        properties:   # this needs to be placed here because that is how some of the Hibernate props are read
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    queries:
        users-query: select username, password from users where username=?
        roles-query: select u.username, r.role from users u inner join user_role ur on(u.id=ur.user_id) inner join role r on(ur.role_id=r.id) where u.username=?
    mail:
        apikey: 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
